/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.*;
import java.util.*;
import dao.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Kuda Terbang
 */
public class register extends javax.swing.JFrame {
    Connector connector;
    /**
     * Creates new form register
     */
    public static String id;
    public static String name;
    public static String username;
    public static String password;
    public static String rpassword;

    public register() {
        initComponents();
        txId.setEnabled(false);
        autonumber();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    private void autonumber() {
        try {
            connector = new Connector();
            Connection connection = connector.getConnection();
            Statement statement = connection.createStatement();
            String sql = "SELECT * FROM users ORDER BY id_user DESC";
            ResultSet result = statement.executeQuery(sql);
            if (result.next()) {
                String NoID = result.getString("id_user");
                String ID = "" + (Integer.parseInt(NoID) + 1);
                txId.setText(ID);
            } else {
                txId.setText("1");
            }
            result.close();
            statement.close();
        } catch (Exception e) {
            // TODO: handle exception
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txUsername = new javax.swing.JTextField();
        txRPassword = new javax.swing.JPasswordField();
        txPassword = new javax.swing.JPasswordField();
        Register = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txName = new javax.swing.JTextField();
        login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(360, 440));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(368, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 368, 50);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel1.setText("HELLO!");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(140, 10, 100, 40);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel2.setText("Please insert your data : ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(109, 62, 143, 16);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel4.setText("Username");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(50, 150, 60, 26);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel5.setText("Password");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(50, 180, 60, 26);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel6.setText("Re-type Password");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(50, 210, 103, 26);

        txUsername.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jPanel2.add(txUsername);
        txUsername.setBounds(220, 150, 120, 20);
        jPanel2.add(txRPassword);
        txRPassword.setBounds(220, 210, 120, 22);
        jPanel2.add(txPassword);
        txPassword.setBounds(220, 180, 120, 22);

        Register.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        Register.setText("Register");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        jPanel2.add(Register);
        Register.setBounds(140, 270, 90, 20);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jLabel7);
        jLabel7.setBounds(80, 240, 220, 20);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel8.setText("Id");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(50, 90, 60, 26);

        txId.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jPanel2.add(txId);
        txId.setBounds(220, 90, 120, 22);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel9.setText("Name");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(50, 120, 60, 26);

        txName.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNameActionPerformed(evt);
            }
        });
        jPanel2.add(txName);
        txName.setBounds(220, 120, 120, 22);

        login.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel2.add(login);
        login.setBounds(140, 300, 90, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 50, 360, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        this.dispose();
         new login().setVisible(true);
    }//GEN-LAST:event_loginActionPerformed

    private void txNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txNameActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RegisterActionPerformed
        // TODO add your handling code here:
        // check the password
        id = txId.getText().toString().trim();
        name = txName.getText().toString().trim();
        username = txUsername.getText().toString().trim();
        password = txPassword.getText().toString().trim();
        rpassword = txRPassword.getText().toString().trim();

        if (!password.equals(rpassword)) {
            JOptionPane.showMessageDialog(null, "Password not match");
        } else if (password.equals("") || username.equals("")) {
            JOptionPane.showMessageDialog(null, "Username or password cannot be empty");
        } else {
            try {
                Connection connection = connector.getConnection();
                String query = "INSERT INTO users VALUES(?,?,?,?)";
                PreparedStatement prepareStatement = connection.prepareStatement(query);
                prepareStatement.setString(1, null);
                prepareStatement.setString(2, password);
                prepareStatement.setString(3, username);
                prepareStatement.setString(4, name);
                prepareStatement.executeUpdate();
                prepareStatement.close();
                connection.close();
                JOptionPane.showMessageDialog(null, "Created successfully");
            } catch (SQLException e) {
                // TODO: handle exception
                System.out.println("error");
            } finally {
                this.dispose();
                login lg = new login();
                lg.setVisible(true);
            }
        }

    }// GEN-LAST:event_RegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login;
    private javax.swing.JTextField txId;
    private javax.swing.JTextField txName;
    private javax.swing.JPasswordField txPassword;
    private javax.swing.JPasswordField txRPassword;
    private javax.swing.JTextField txUsername;
    // End of variables declaration//GEN-END:variables
}
